//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4913
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading;
using SMART.Core.Interfaces;

namespace SMART.Demo.TestModel
{
    public class Testclass : IDisposable, IDefectDetected
    {

        public event EventHandler DefectDetected;

        public virtual void AToB_StartToD(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("AToB_StartToD executed");
        }

        public virtual void BToC_EToStop(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("BToC_EToStop executed");
        }

        public virtual void Start()
        {

            Thread.Sleep(100);
            Console.WriteLine("Start verified");
        }

        public virtual void Stop()
        {

            Thread.Sleep(100);
            Console.WriteLine("stop verified");
        }

        public virtual void A()
        {
            Thread.Sleep(100);
            InvokeDefectDetected(EventArgs.Empty);
            Console.WriteLine("A verified");
        }

        public virtual void C()
        {

            Thread.Sleep(100);
            Console.WriteLine("C verified");
        }

        public virtual void D()
        {

            Thread.Sleep(100);
            Console.WriteLine("D verified");
        }

        public virtual void E()
        {

            Thread.Sleep(100);
            Console.WriteLine("E verified");
        }


        public virtual void F()
        {

            Thread.Sleep(100);
            Console.WriteLine("F verified");
        }
        public virtual void startToA(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("Start to A executed");
        }

        public virtual void AToB(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("A to B executed");

        }

        public virtual void DToE(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("D to E executed");

        }

        public virtual void BToC(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("B to C executed");

        }

        public virtual void CToStop(params string[] parameters)
        {
            Thread.Sleep(100);
            Console.WriteLine("C to Stop executed");

        }

        public void Dispose()
        {
            Console.WriteLine("Dispose testclass");
        }

        private void InvokeDefectDetected(EventArgs e)
        {
            EventHandler detected = DefectDetected;
            if (detected != null) detected(this, e);
        }
    }
}

